- name: Hello World Sample
  hosts: all
  vars: 
    arcon_cred:
      username: '{{ lookup("env","pass") }}'
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!{{ arcon_cred }}"

