- name: Hello World Sample
  hosts: all
  vars: 
    arcon_cred:
      username: '{{ look_up("env","user") }}'
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!{{ arcon_cred }}"

