- name: Hello World Sample
  hosts: all
  vars: 
    machine:
      username: '{{ ansible_user }}'
    arcon_cred:
      user: '{{ lookup("env","Username") }}'
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!{{ username }}"

